# Generated by Django 2.0.6 on 2020-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总价'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='课程原价'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='课程实价'),
        ),
    ]
