# Generated by Django 3.0 on 2020-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day04', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='restatur',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
