# Generated by Django 3.0 on 2020-07-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'ems_emp',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ems_user',
            },
        ),
    ]
